name: Github Actor Windows

on:
  push:

  
jobs:
  job1:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run a multi-line script
        run: |
          echo ${env:GITHUB_EVENT_NAME}
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git status
          cd public
          ni "${env:GITHUB_SHA}_actor.txt"
          echo "Name:- ${env:GITHUB_ACTOR}" > ${env:GITHUB_SHA}_actor.txt
          git pull
          git add .
          git status
          git commit -m "new file created"
          git status
          git push
