name: Upload new files

on:
  push:
  pull_request:

  
jobs:
  job1:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run a multi-line script
        run: |
          echo "PATCH-3 BRANCH"
          echo "$GITHUB_REF"
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          pwd
          git status
          cd public
          ni "${GITHUB_SHA}.txt"
          echo "Name:- $GITHUB_ACTOR" > ${GITHUB_SHA}.txt
          echo "Email:- ${{github.event.inputs.email}}" >> "${GITHUB_SHA}.txt"
          git add .
          git commit -m "new file created"
          git push
