name: Run Commands

on:
  push
  
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo Hello, world!
        id: Run_script

      - name: Run a multi-line script
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          pwd
          git status
          touch hello.txt
          git checkout main
          git status
          git add .
          git status
          git commit -m "new file created"
          git status         
          python3 test.py
