name: Testing using branches for checkout action

on:
  push
  
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run a multi-line script
        run: |
          echo "MAIN BRANCH"
          git checkout patch-2-checkout
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          pwd
          git status
          cd public
          touch "${GITHUB_SHA}.txt"
          echo "Name:- ${ GITHUB_ACTOR } > ${GITHUB_SHA}.txt
          echo "Email:- ${ GITHUB_ACTOR} >> "${GITHUB_SHA}.txt"
          git checkout main
          git add .
          git commit -m "new file created"
          git push

