name: Upload new files

on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        default: 'World'
        required: true
      email: 
        description: "Person's email address"
        required: true

  
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run a multi-line script
        run: |
          echo "PATCH-2 BRANCH"
          echo "$GITHUB_CONTEXT"
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          pwd
          git status
          cd public
          touch "${GITHUB_SHA}.txt"
          echo "Name:- ${{ github.event.inputs.name }}" > ${GITHUB_SHA}.txt
          echo "Email:- ${{github.event.inputs.email}}" >> "${GITHUB_SHA}.txt"
          git add .
          git commit -m "new file created"
          git push
